
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programCOMMA EQUAL ID IF LBRACE LPAREN MAIN NUMBER OPBIN RBRACE RETURN RPAREN SEMICOLUMN WHILE program : MAIN LPAREN variables RPAREN LBRACE command RETURN expression SEMICOLUMN RBRACE\n    \n    variables : ID\n              | ID COMMA variables\n    command : ID EQUAL expression\n\t       | WHILE LPAREN expression RPAREN LBRACE command RBRACE\n               | command SEMICOLUMN command\n    expression : ID\n                | NUMBER\n                | expression OPBIN expression'
    
_lr_action_items = {'MAIN':([0,],[2,]),'$end':([1,26,],[0,-1,]),'LPAREN':([2,12,],[3,16,]),'ID':([3,7,8,13,14,15,16,24,28,],[5,5,11,18,11,18,18,18,11,]),'RPAREN':([4,5,9,18,19,22,27,],[6,-2,-3,-7,-8,25,-9,]),'COMMA':([5,],[7,]),'LBRACE':([6,25,],[8,28,]),'WHILE':([8,14,28,],[12,12,12,]),'RETURN':([10,18,19,20,21,27,30,],[13,-7,-8,-6,-4,-9,-5,]),'SEMICOLUMN':([10,17,18,19,20,21,27,29,30,],[14,23,-7,-8,14,-4,-9,14,-5,]),'EQUAL':([11,],[15,]),'NUMBER':([13,15,16,24,],[19,19,19,19,]),'OPBIN':([17,18,19,21,22,27,],[24,-7,-8,24,24,24,]),'RBRACE':([18,19,20,21,23,27,29,30,],[-7,-8,-6,-4,26,-9,30,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'variables':([3,7,],[4,9,]),'command':([8,14,28,],[10,20,29,]),'expression':([13,15,16,24,],[17,21,22,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> MAIN LPAREN variables RPAREN LBRACE command RETURN expression SEMICOLUMN RBRACE','program',10,'p_program','Semantics.py',127),
  ('variables -> ID','variables',1,'p_variables','Semantics.py',134),
  ('variables -> ID COMMA variables','variables',3,'p_variables','Semantics.py',135),
  ('command -> ID EQUAL expression','command',3,'p_command','Semantics.py',147),
  ('command -> WHILE LPAREN expression RPAREN LBRACE command RBRACE','command',7,'p_command','Semantics.py',148),
  ('command -> command SEMICOLUMN command','command',3,'p_command','Semantics.py',149),
  ('expression -> ID','expression',1,'p_expression','Semantics.py',165),
  ('expression -> NUMBER','expression',1,'p_expression','Semantics.py',166),
  ('expression -> expression OPBIN expression','expression',3,'p_expression','Semantics.py',167),
]
